import docx
from docx.shared import Inches, Pt, RGBColor
from typing import Dict, Any

class DOCXReportGenerator:
    @staticmethod
    def generate(file_path: str, data: Dict[str, Any]):
        """
        Generate a professional Word (DOCX) student risk assessment report.
        """
        doc = docx.Document()
        
        student = data["student"]
        prediction = data["prediction"]
        recommendation = data["recommendation"]
        review = data["review"]
        narrative = data["narrative"]
        
        # Define clean, professional color palette
        primary_color = RGBColor(26, 54, 93)   # Deep Slate Blue
        secondary_color = RGBColor(43, 108, 176) # Medium Blue
        accent_color = RGBColor(197, 48, 48)   # Soft Red (Risk)
        charcoal = RGBColor(45, 55, 72)
        muted_gray = RGBColor(113, 128, 150)
        
        # --- Helper: Apply heading styling ---
        def add_heading(text, level, color, size_pt):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(12)
            p.paragraph_format.space_after = Pt(4)
            p.paragraph_format.keep_with_next = True
            run = p.add_run(text)
            run.font.name = 'Arial'
            run.font.size = Pt(size_pt)
            run.font.bold = True
            run.font.color.rgb = color
            return p

        # --- Document Title ---
        title_p = doc.add_paragraph()
        title_p.paragraph_format.space_after = Pt(4)
        title_run = title_p.add_run("EduPilot AI Student Risk Assessment")
        title_run.font.name = 'Arial'
        title_run.font.size = Pt(20)
        title_run.font.bold = True
        title_run.font.color.rgb = primary_color
        
        meta_p = doc.add_paragraph()
        meta_p.paragraph_format.space_after = Pt(18)
        meta_run = meta_p.add_run(f"Generated on {data['generated_at'].strftime('%Y-%m-%d %H:%M:%S')}")
        meta_run.font.size = Pt(9)
        meta_run.font.italic = True
        meta_run.font.color.rgb = muted_gray

        # --- 1. Student Information ---
        add_heading("1. Student Information", 1, secondary_color, 14)
        
        table = doc.add_table(rows=3, cols=2)
        table.autofit = False
        table.columns[0].width = Inches(3.0)
        table.columns[1].width = Inches(3.5)
        
        cells_data = [
            (f"Student Name: {student.first_name} {student.last_name}", f"Student Code: {student.student_code}"),
            (f"Age: {student.age}", f"Gender: {student.gender}"),
            (f"School: {'Gabriel Pereira (GP)' if student.school == 'GP' else 'Mousinho da Silveira (MS)'}", f"Assessment ID: {prediction.id[:8].upper()}")
        ]
        
        for idx, (val1, val2) in enumerate(cells_data):
            row = table.rows[idx]
            r1 = row.cells[0].paragraphs[0].add_run(val1)
            r2 = row.cells[1].paragraphs[0].add_run(val2)
            r1.font.name = 'Arial'
            r2.font.name = 'Arial'
            r1.font.size = Pt(10)
            r2.font.size = Pt(10)
            
        doc.add_paragraph() # spacing

        # --- 2. Predictive Model Assessment ---
        add_heading("2. Predictive Model Assessment", 1, secondary_color, 14)
        
        p = doc.add_paragraph()
        r = p.add_run("Risk Classification: ")
        r.bold = True
        r_val = p.add_run(prediction.risk_level)
        r_val.bold = True
        r_val.font.color.rgb = accent_color if prediction.risk_level == "HIGH_RISK" else RGBColor(56, 161, 105)
        
        p2 = doc.add_paragraph()
        r = p2.add_run(f"Model Confidence: {prediction.confidence:.1%}\n")
        r.font.size = Pt(10)
        probs_str = f"Class Probabilities: LOW_RISK: {prediction.class_probabilities.get('LOW_RISK', 0.0):.1%} | MEDIUM_RISK: {prediction.class_probabilities.get('MEDIUM_RISK', 0.0):.1%} | HIGH_RISK: {prediction.class_probabilities.get('HIGH_RISK', 0.0):.1%}\n"
        r2 = p2.add_run(probs_str)
        r2.font.size = Pt(10)
        r3 = p2.add_run(f"Model Version: {prediction.model_version}")
        r3.font.size = Pt(10)
        
        note_p = doc.add_paragraph()
        note_run = note_p.add_run("Prediction generated by the EduPilot ANN risk classification model.")
        note_run.font.size = Pt(8.5)
        note_run.font.italic = True
        note_run.font.color.rgb = muted_gray

        # --- 3. Explainable AI (SHAP) Analysis ---
        add_heading("3. Explainable AI (SHAP) Analysis", 1, secondary_color, 14)
        
        add_heading("Primary Risk Contributing Factors:", 2, charcoal, 11)
        for factor in prediction.risk_factors:
            dp = doc.add_paragraph(style='List Bullet')
            dp.paragraph_format.space_after = Pt(2)
            run = dp.add_run(factor)
            run.font.name = 'Arial'
            run.font.size = Pt(10)
            
        add_heading("Primary Protective Elements:", 2, charcoal, 11)
        for factor in prediction.protective_factors:
            dp = doc.add_paragraph(style='List Bullet')
            dp.paragraph_format.space_after = Pt(2)
            run = dp.add_run(factor)
            run.font.name = 'Arial'
            run.font.size = Pt(10)

        # --- 4. Multimodal Evidence Synthesis ---
        add_heading("4. Multimodal Evidence Synthesis", 1, secondary_color, 14)
        
        add_heading("AI Executive Analysis:", 2, charcoal, 11)
        p_exec = doc.add_paragraph()
        run = p_exec.add_run(narrative.get("executive_summary", ""))
        run.font.name = 'Arial'
        run.font.size = Pt(10)
        
        p_synth = doc.add_paragraph()
        run = p_synth.add_run(narrative.get("evidence_synthesis", ""))
        run.font.name = 'Arial'
        run.font.size = Pt(10)

        # --- 5. AI Co-Pilot Recommendation ---
        add_heading("5. AI Co-Pilot Recommendation", 1, secondary_color, 14)
        
        title_rec = f"Proposed Plan: {recommendation.get('title', 'N/A')} (Priority: {recommendation.get('priority', 'N/A')})"
        add_heading(title_rec, 2, charcoal, 11)
        
        p_rec = doc.add_paragraph()
        run = p_rec.add_run(f"Plan Summary: {recommendation.get('summary', 'N/A')}")
        run.font.name = 'Arial'
        run.font.size = Pt(10)
        
        add_heading("Recommended Intervention Actions:", 2, charcoal, 11)
        for action in recommendation.get("recommended_actions", []):
            dp = doc.add_paragraph(style='List Bullet')
            dp.paragraph_format.space_after = Pt(2)
            run = dp.add_run(action)
            run.font.name = 'Arial'
            run.font.size = Pt(10)
            
        add_heading("Monitoring and Milestones:", 2, charcoal, 11)
        for plan in recommendation.get("monitoring_plan", []):
            dp = doc.add_paragraph(style='List Bullet')
            dp.paragraph_format.space_after = Pt(2)
            run = dp.add_run(plan)
            run.font.name = 'Arial'
            run.font.size = Pt(10)

        p_period = doc.add_paragraph()
        run = p_period.add_run(f"Review Period: {recommendation.get('review_period_days', 14)} days")
        run.font.name = 'Arial'
        run.font.size = Pt(10)

        # --- 6. Human Educator Review ---
        add_heading("6. Human Educator Review", 1, secondary_color, 14)
        
        table_rev = doc.add_table(rows=4, cols=2)
        table_rev.autofit = False
        table_rev.columns[0].width = Inches(2.5)
        table_rev.columns[1].width = Inches(4.0)
        
        rev_cells = [
            ("Educator Review Status", review["status"]),
            ("Reviewed By", review["reviewed_by"]),
            ("Decision Date", review["reviewed_at"]),
            ("Educator Comments", review["educator_comment"])
        ]
        
        if review["status"] == "REJECTED":
            rev_cells.append(("Rejection Reason", review["rejection_reason"]))
            
        if review["status"] == "MODIFIED":
            mod = review["modified_recommendation"]
            rev_cells.append(("Modification Details", f"Title: {mod.get('title')}\nSummary: {mod.get('summary')}"))
            
        # Re-initialize row dimensions to match size
        if len(rev_cells) > 4:
            for _ in range(len(rev_cells) - 4):
                table_rev.add_row()
                
        for idx, (label, val) in enumerate(rev_cells):
            row = table_rev.rows[idx]
            r1 = row.cells[0].paragraphs[0].add_run(label)
            r2 = row.cells[1].paragraphs[0].add_run(val)
            r1.font.bold = True
            r1.font.size = Pt(10)
            r2.font.size = Pt(10)
            
        doc.add_paragraph() # spacing
        
        # --- Disclaimer ---
        doc.add_paragraph()
        disc_p = doc.add_paragraph()
        disc_run_title = disc_p.add_run("Disclaimer:\n")
        disc_run_title.font.bold = True
        disc_run_title.font.size = Pt(8)
        disc_run_title.font.color.rgb = muted_gray
        
        disc_run = disc_p.add_run(
            "EduPilot AI is a decision-support system. Predictions and AI-generated recommendations are "
            "intended to assist qualified educators and academic advisors. Final academic intervention "
            "decisions remain the responsibility of the educational institution and authorized personnel."
        )
        disc_run.font.size = Pt(8)
        disc_run.font.color.rgb = muted_gray
        disc_run.font.italic = True
        
        # Save Document
        doc.save(file_path)
