# Risk Level Constants
LOW_RISK = "LOW_RISK"
MEDIUM_RISK = "MEDIUM_RISK"
HIGH_RISK = "HIGH_RISK"

RISK_LEVELS = [LOW_RISK, MEDIUM_RISK, HIGH_RISK]

# Human Review Status Constants
PENDING_REVIEW = "PENDING_REVIEW"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
MODIFIED = "MODIFIED"

REVIEW_STATUSES = [PENDING_REVIEW, APPROVED, REJECTED, MODIFIED]

# Intervention priorities
PRIORITY_LOW = "LOW"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_HIGH = "HIGH"

INTERVENTION_PRIORITIES = [PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH]
